# Numpy Axis and Random.
# Objective.
# 1. Concatenate
# 2. Sum
# See how to use random.

In [2]:
import numpy as np
np.__version__

'1.26.4'

In [3]:
# Matrix Transpose.
myArray = np.array([[1,2,3,4], [2,4,6,10]])
myArray

array([[ 1,  2,  3,  4],
       [ 2,  4,  6, 10]])

In [4]:
# print the transpose matrix.
print(myArray.T)

[[ 1  2]
 [ 2  4]
 [ 3  6]
 [ 4 10]]


In [7]:
# Reshaping with - 1.

myArray = np.array(
    [[1, 2, 3, 4],
     [2, 4, 6, 10]]
)
print(myArray.reshape(-1))

[ 1  2  3  4  2  4  6 10]


In [15]:
# Reshape the input array into (3, 80).

myArray = np.empty((3, 4, 2, 10))

print(myArray.shape)

print(myArray.reshape(3, -1).shape)

(3, 4, 2, 10)
(3, 80)


In [16]:
print(np.ones((3, 4, 2, 2)).reshape(2, -1, 2).shape)

(2, 12, 2)


In [18]:
# Create an empty numpy array with shape (4, 2)
my_np_array = np.empty((4, 2))

In [21]:
# Print the entire array to check its contents
print("The entire numpy array:")
print(my_np_array)

The entire numpy array:
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]
 [9.9e-324 2.0e-323]
 [3.0e-323 4.9e-323]]


In [22]:
# Print the first row (row index 0) to extract all its elements
print("First row of the numpy array:")
print(my_np_array[0, :])

First row of the numpy array:
[5.e-324 1.e-323]


In [23]:
#  Print the first column (column index 0) as a 2D array
print("First column of the numpy array:")
print(my_np_array[:, [0]])

First column of the numpy array:
[[4.9e-324]
 [1.5e-323]
 [9.9e-324]
 [3.0e-323]]


# Create an empty numpy array with shape (3, 4, 2)
# Print the shape of the subarray by selecting specific slices
# Select all elements along the first axis (:), rows with indices 0 and 2 ([0, 2]) along the second axis,
# and all elements along the third axis (:).

In [26]:
print("The shape of the selected subarray (rows 0 and 2 from the second axis):")
print(my_np_array[:, [0, 2], :].shape)

The shape of the selected subarray (rows 0 and 2 from the second axis):
(3, 2, 2)


In [28]:
# Create a 2D array filled with 1s (2 rows, 3 columns)
my_2d_array_1 = np.array(
    [[1, 1, 1],
     [1, 1, 1]]
)

# Create another 2D array filled with 2s (2 rows, 3 columns)
my_2d_array_2 = np.array(
    [[2, 2, 2],
     [2, 2, 2]]
)

# Concatenate the two arrays along the second axis (columns) to form a single array
# The result will have the same number of rows (2) but more columns (6).
my_2d_array_joined = np.concatenate(
    (my_2d_array_1, my_2d_array_2),
    axis=1
)

# Print the concatenated array to verify the result
print("Concatenated array:")
print(my_2d_array_joined)

# Print the shape of the first array to confirm its dimensions
print("Shape of my_2d_array_1 (rows, columns):", my_2d_array_1.shape)

# Print the shape of the second array to confirm its dimensions
print("Shape of my_2d_array_2 (rows, columns):", my_2d_array_2.shape)

# Print the shape of the concatenated array to confirm the result of concatenation
print("Shape of my_2d_array_joined (rows, columns):", my_2d_array_joined.shape)


Concatenated array:
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]
Shape of my_2d_array_1 (rows, columns): (2, 3)
Shape of my_2d_array_2 (rows, columns): (2, 3)
Shape of my_2d_array_joined (rows, columns): (2, 6)


# 3D Array..

In [29]:
# Create a 3D array with shape (4, 2, 10), filled with uninitialized values
my_md_array_1 = np.empty((4, 2, 10))

In [30]:
# Create another 3D array with the same shape (4, 2, 10), filled with uninitialized values
my_md_array_2 = np.empty((4, 2, 10))


In [32]:
# Concatenate the two 3D arrays along the first axis (axis=0)
# This increases the size of the first axis from 4 to 8 while keeping the other dimensions the same
my_md_array_joined = np.concatenate(
    (my_md_array_1, my_md_array_2),
    axis=0,
)

In [33]:
# Print the shape of the resulting concatenated array to verify the result
print("Shape of the concatenated 3D array:")
print(my_md_array_joined.shape)

Shape of the concatenated 3D array:
(8, 2, 10)


 # Sum => aggregation

In [34]:
# Create a 2D numpy array with 2 rows and 3 columns
my_np_array = np.array(
    [[1, 5, -2],
     [0, 1, 9]]
)

In [35]:
# Print the shape of the array to confirm its dimensions (rows, columns)
print("Shape of the array (rows, columns):")
print(my_np_array.shape)

Shape of the array (rows, columns):
(2, 3)


In [36]:
# Calculate the sum of the elements along each column (axis=0)
# This will produce a 1D array where each value is the sum of a column
print("Sum of elements along each column:")
print(np.sum(my_np_array, axis=0))

Sum of elements along each column:
[1 6 7]


In [37]:
# Print the shape of the resulting array after summing along columns
# Since it sums over rows, the result will be a 1D array with 3 elements (one for each column)
print("Shape of the summed array:")
print(np.sum(my_np_array, axis=0).shape)

Shape of the summed array:
(3,)


In [38]:
# Create a 4D numpy array with shape (2, 4, 12, 10), filled with uninitialized values
my_np_array = np.empty((2, 4, 12, 10))

In [39]:
# Calculate the sum of the elements along the third axis (axis=2)
# This reduces the third dimension (size 12) by summing its elements, resulting in a new shape
print("Shape of the array after summing along the third axis (axis=2):")
print(np.sum(my_np_array, axis=2).shape)


Shape of the array after summing along the third axis (axis=2):
(2, 4, 10)


""" Random
- rand()
- randint()
"""

In [42]:
print("A single random float between 0 and 1:")
print(np.random.rand())
print("A 4x2 array of random floats between 0 and 1:")
print(np.random.rand(4,2))
print("A single random integer between 0 and 99:")
print(np.random.randint(100))
print("A 5x3 array of random integers between 0 and 99:")
print(np.random.randint(100, size=(5,3)))

A single random float between 0 and 1:
0.9264638690498818
A 4x2 array of random floats between 0 and 1:
[[0.73875156 0.59003121]
 [0.09824504 0.96215077]
 [0.7355102  0.22324309]
 [0.61827967 0.77945728]]
A single random integer between 0 and 99:
64
A 5x3 array of random integers between 0 and 99:
[[16 61 72]
 [22 42 19]
 [75 91 16]
 [77 57 52]
 [23 16 53]]


In [43]:
# Random shuffle

np.random.seed(42)

my_array = np.random.randint(5, size=(5,))
print(my_array)
np.random.shuffle(my_array)
print(my_array)

[3 4 2 4 4]
[4 3 4 2 4]


In [44]:
""" Use case: Split Dataset into Train, Test and Validation
"""

dataset = np.random.rand(1000, 5)
print("Dataset:\n", dataset[:5])


Dataset:
 [[4.59248892e-01 3.33708611e-01 1.42866818e-01 6.50888473e-01
  5.64115790e-02]
 [7.21998772e-01 9.38552709e-01 7.78765841e-04 9.92211559e-01
  6.17481510e-01]
 [6.11653160e-01 7.06630522e-03 2.30624250e-02 5.24774660e-01
  3.99860972e-01]
 [4.66656632e-02 9.73755519e-01 2.32771340e-01 9.06064345e-02
  6.18386009e-01]
 [3.82461991e-01 9.83230886e-01 4.66762893e-01 8.59940407e-01
  6.80307539e-01]]


In [45]:
np.random.shuffle(dataset)

In [46]:
dataset[:5]

array([[0.27561234, 0.7871266 , 0.97483465, 0.37120709, 0.42888688],
       [0.01363402, 0.32272657, 0.55435668, 0.14821746, 0.09209875],
       [0.87426247, 0.51010971, 0.72340477, 0.10413736, 0.22543876],
       [0.32350039, 0.83430337, 0.62929881, 0.19885628, 0.06461668],
       [0.55835232, 0.86993783, 0.37154651, 0.61440001, 0.52366342]])

In [47]:
""" Step 2. Split """

index_1 = int(0.8 * len(dataset))
index_2 = int(0.9 * len(dataset))

trainset, valset, testset = np.split(
    dataset,
    [index_1, index_2],
)
print(len(trainset), len(valset), len(testset))

800 100 100


In [8]:
# argmax().
# return the index where the value is maximum.

one = np.array([1,2,44,22,3,2,3222])

In [10]:
one.argmax()

6

In [11]:
one.argmin()

0

In [12]:
# argsort() - return the index array in sorted oder.

one.argsort()

array([0, 1, 5, 4, 3, 2, 6])

In [14]:
# argsort().
one.argsort()

array([0, 1, 5, 4, 3, 2, 6])