# Basic Numpy.
## Joy Shib.

"""
NumPy: The Basics
=================

NumPy stands for Numerical Python and is a powerful library in Python designed for numerical computations.
It provides high-performance multidimensional array objects and tools for working with these arrays efficiently.

Key Features:
-------------
- **High Performance**: Up to 50 times faster than Python lists.
- **Memory Efficiency**: Uses contiguous blocks of memory for storage.
- **Support for Vectorization**: Eliminates the need for explicit loops.
- **Wide Usage**: Ideal for numerical and scientific computations.

Prerequisites:
--------------
- Familiarity with Jupyter Notebook.
- Basic understanding of Python.

Objectives:
-----------
By the end of this session, you will be able to:
1. Use Jupyter Notebook for running NumPy operations.
2. Create and manipulate NumPy arrays.
3. Understand and apply NumPy indexing.
4. Slice and work with subsets of a NumPy array.
there are so many significant features are available in Numpy.

Let's get started with exploring NumPy!
"""


In [1]:
import numpy as np

np.__version__

'1.26.4'

In [2]:
# Numpy array decleartion.
import numpy as np
A = np.array([1,2,3,4,5,6,7,8,9,10])
print(A)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# print the data-type of array.
print(type(A))

<class 'numpy.ndarray'>


In [4]:
print(A.dtype)

int64


In [5]:
# print the shape..
print(A.shape)

(10,)


In [27]:
# print the ndim.
# ndim -> number of dimentions.
print(A.ndim)

1


In [7]:
# Create an array with all zeros..


zeros_np = np.zeros(
    shape=(5,)
)

zeros_np

array([0., 0., 0., 0., 0.])

In [8]:
# Create an array wirh all ones.

ones_np = np.ones (
    shape = (5,)
)
ones_np

array([1., 1., 1., 1., 1.])

In [11]:
# another approch.
ones_np_array = np.ones (
    shape = (10,3),
    dtype = 'int'
)
print(ones_np_array)
print(ones_np_array.dtype)


[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
int64


In [17]:
# Create an array with specific values.
# user value define korte caile 'fill_value' use korte hbe.


specifiac_np_array = np.full (
    shape = (10,4),
   # dtype='int'
    fill_value = 100,

)
specifiac_np_array

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [19]:
# Create an identity matrix.

identity_matrix = np.eye(
    10

)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [22]:
# Create an empty array.

empty_array = np.empty(
    shape = (10,3),
)
empty_array

array([[3.14820295e-316, 0.00000000e+000, 3.86598877e+233],
       [2.31634000e-152, 2.31596508e+251, 2.46175026e+198],
       [2.31261087e-152, 5.98736697e+247, 6.01334637e-154],
       [3.04284970e+169, 6.89806196e+212, 1.54381037e+256],
       [8.90385429e+252, 6.01334515e-154, 6.55490914e-260],
       [6.01347002e-154, 4.19321854e+228, 1.14490518e+243],
       [6.03425842e-154, 1.27826910e-152, 1.06098610e-153],
       [1.10638927e+200, 3.65591182e+233, 3.06295040e+262],
       [1.39539405e-258, 6.01347002e-154, 1.35616577e+248],
       [5.72631091e+188, 1.39620200e-308, 6.85384601e-310]])

In [23]:
my_empty_np_array = np.empty(
    shape=(5,)
)
my_empty_np_array

array([1., 1., 1., 1., 1.])

In [24]:
# Create a sequential array
# arange
# linspace

my_array = np.arange(1, 10)
print(my_array)

my_np_array = np.linspace(
    start=0,
    stop=10,
    num=5
)
print(my_np_array)

[1 2 3 4 5 6 7 8 9]
[ 0.   2.5  5.   7.5 10. ]


In [25]:
"""Type cast
"""

my_empty_np_array_int = my_empty_np_array.astype('int')
print(my_empty_np_array_int)

[1 1 1 1 1]


In [26]:
# A 0-dimensional array (scalar) containing a single value.
my_0d_array = np.array(42)
print('0-dimensional array:', my_0d_array, 'ndim:', my_0d_array.ndim)

# A 1-dimensional array (vector) containing a sequence of numbers.
my_1d_array = np.array(
    [1.5, 2, 3.3, 4.7, 5.1, 6]
)
print('1-dimensional array:', my_1d_array, 'ndim:', my_1d_array.ndim)

# A 2-dimensional array (matrix) containing rows and columns of numbers.
my_2d_array = np.array(
    [[1, 2, 3, 4],
     [5, 8, 9, 5],
     [7, 1, 2, 7]]
)
print('2-dimensional array', 'ndim:', my_2d_array.ndim)
print(my_2d_array)

0-dimensional array: 42 ndim: 0
1-dimensional array: [1.5 2.  3.3 4.7 5.1 6. ] ndim: 1
2-dimensional array ndim: 2
[[1 2 3 4]
 [5 8 9 5]
 [7 1 2 7]]


In [29]:

# Creating an 1-dimensional NumPy array.
my_np_array = np.array(
    [1, 2, 3, 4, 5]
)

# Accessing the 3rd element (index 2) using non-negative indexing.
print(my_np_array[2])  # Expected Output: 3

# Accessing the 3rd element from the end (index -3) using negative indexing.
print(my_np_array[-3])  # Expected Output: 3


3
3


In [30]:

# Creating a 2-dimensional NumPy array (matrix)
my_2d_array = np.array(
    [[1, 2, 3, 4],
     [5, 8, 9, 5],
     [7, 1, 2, 7]]
)

# Accessing the element at row 1, column 1 (0-based indexing)
print(my_2d_array[1, 1])  # Expected output: 8

# Accessing the element at row 1, 2nd column from the start (negative indexing for columns)
print(my_2d_array[1, -3])  # Expected output: 8


8
8


In [33]:

# 1-dimensional array for slicing examples
my_1d_array = np.array([1.5, 2, 3.3, 4.7, 5.1, 6])

# 2-dimensional array for slicing examples
my_2d_array = np.array(
    [[1, 2, 3, 4],
     [5, 8, 9, 5],
     [7, 1, 2, 7]]
)

# Slicing the entire array: default start=0, end=n, step=1
print("Entire 1D array:", my_1d_array[::])  # Output: [1.5, 2, 3.3, 4.7, 5.1, 6]

# Slicing elements from index 2 to 4 (end index is excluded)
print("Elements from index 2 to 4 (exclusive):", my_1d_array[2:5])  # Output: [3.3, 4.7, 5.1]

# Slicing elements from index 1 to 4 with a step of 2
print("Elements from index 1 to 4 with a step of 2:", my_1d_array[1:5:2])  # Output: [2, 4.7]

# Slicing a sub-matrix: rows 0 to 1 and columns 1 to 2 (end index excluded)
print("Sub-matrix with rows 0 to 1 and columns 1 to 2:")
print(my_2d_array[0:2, 1:3])



Entire 1D array: [1.5 2.  3.3 4.7 5.1 6. ]
Elements from index 2 to 4 (exclusive): [3.3 4.7 5.1]
Elements from index 1 to 4 with a step of 2: [2.  4.7]
Sub-matrix with rows 0 to 1 and columns 1 to 2:
[[2 3]
 [8 9]]


In [34]:
print(my_2d_array)

[[1 2 3 4]
 [5 8 9 5]
 [7 1 2 7]]


In [35]:
print(my_2d_array[1:3,])

[[5 8 9 5]
 [7 1 2 7]]
