# Numpy Basic-02.
## Joy Shib.

In [1]:
""" Numpy - Useful Methods

Objectives:

1. We will filter elements from a numpy array
3. We will reshape, sort, iterate over a numpy array
4. We will learn important numpy functions
   4.1. argmax, argmin => finds the index of an max element in a numpy array
   4.2. split => splits a numpy array into different arrays
   4.3. dot, transpose (T)
   4.4. mean, median, std => generate statistical values
6. We will understand vectorization
7. We will understand Broadcasting
"""

import numpy as np

np.__version__

'1.26.4'

In [3]:
"""numpy filter
- using boolean mask
- using conditionals
- using indices
- using custom filter method
"""

my_1d_array = np.array(
    [1, 2, 3, 4, 5, 6]
)



In [5]:
# using boolean.
# look the output, 'true' values are considered here.

filter_mask = [True, False, True, False, True, False]
my_1d_array[filter_mask]

array([1, 3, 5])

In [7]:
# using conditionals.
filter_mask = my_1d_array >= 3
my_1d_array[filter_mask]

array([3, 4, 5, 6])

In [9]:
# we can create a new array and make this changes.
new_array = my_1d_array[filter_mask]
print(new_array)

[3 4 5 6]


In [12]:
# indicies..
# it's shows that where my condition become true and then print this index.
indices = np.where(my_1d_array % 2 == 0)
print(indices)

(array([1, 3, 5]),)


In [14]:
# show this values where my index is belong to. like, -> a[ind].
new_idicies = my_1d_array[indices]
print(new_idicies)

[2 4 6]


In [18]:

# 1-dimensional NumPy array.
my_1d_array = np.array([1, 2, 3, 4, 5, 6])

# Custom filter method to filter even numbers.
def my_filter_method(x):
    # Logic: Return True for even numbers, False otherwise
    return x % 2 == 0

# Using the filter function with the custom filter method
filters_iterable = filter(my_filter_method, my_1d_array)

# Converting the filtered result (an iterable) to a NumPy array
my_filt_array = np.array(list(filters_iterable))

# Display the filtered array
print("Filtered array using custom filter method:", my_filt_array) # Output: [2, 4, 6]



Filtered array using custom filter method: [2 4 6]


In [20]:

# Creating a 2-dimensional NumPy array filled with the value 5
my_2d_array = np.full(
    shape=(5, 3),  # Original shape: 5 rows and 3 columns
    dtype='int',   # Data type: integer
    fill_value=5   # Fill value: 5
)

# Reshaping the array to a new shape (3 rows and 5 columns)
# Condition: Total elements before and after reshaping must remain the same (5*3 = 15)
my_np_array_reshaped = my_2d_array.reshape(3, 5)

# Printing the original array and its shape.
print("Original 2D array:")
print(my_2d_array)
print("Shape of original array:", my_2d_array.shape)

# Printing the reshaped array and its new shape
print("\nReshaped 2D array:")
print(my_np_array_reshaped)
print("Shape of reshaped array:", my_np_array_reshaped.shape)


Original 2D array:
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
Shape of original array: (5, 3)

Reshaped 2D array:
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
Shape of reshaped array: (3, 5)


In [21]:
# Numpy reshape
# Step 1. flattening -> 1D
# Step 2. reshaping.

print(my_2d_array)
print(my_2d_array.flatten())
print(my_2d_array.reshape(3, 5, 1))

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
[[[5]
  [5]
  [5]
  [5]
  [5]]

 [[5]
  [5]
  [5]
  [5]
  [5]]

 [[5]
  [5]
  [5]
  [5]
  [5]]]


In [22]:
# Reshaping with -1.

np.ones((3, 4, 2, 2)).reshape(2, -1, 2).shape

(2, 12, 2)

In [24]:
# Sort..
prediction = [0.3, 0.1, 0.4]
print(np.sort(prediction)) # sort in accending order.
print(np.sort(prediction)[::-1]) # sort in decending order.

[0.1 0.3 0.4]
[0.4 0.3 0.1]


In [35]:

my_1d_array = np.array([1.5, 2, 3.3, 4.7, 5.1, 6])

# Print the original array before starting iterations
print('Original array for iteration:', my_1d_array)

# Iterate by value
print('\nIterating by value:')
for x in my_1d_array:
    print(x, end=', ')
print()  # Move to the next line after printing all values

# Iterate by index
print('\nIterating by index:')
for i in range(len(my_1d_array)):
    print(my_1d_array[i], end=', ')
print()  # Move to the next line after printing all values

# Enumerate: Iterate by both index and value
print('\nIterating with enumerate (index and value):')
for i, x in enumerate(my_1d_array):
    print(i, x)


Original array for iteration: [1.5 2.  3.3 4.7 5.1 6. ]

Iterating by value:
1.5, 2.0, 3.3, 4.7, 5.1, 6.0, 

Iterating by index:
1.5, 2.0, 3.3, 4.7, 5.1, 6.0, 

Iterating with enumerate (index and value):
0 1.5
1 2.0
2 3.3
3 4.7
4 5.1
5 6.0


In [37]:
my_1d_array = np.array([1.5, 2, 3.3, 4.7, 5.1, 6])

# Finding the index of the maximum value in the array
index_max = np.argmax(my_1d_array)
# Finding the index of the minimum value in the array
index_min = np.argmin(my_1d_array)

print(f"Index of maximum value: {index_max}, Index of minimum value: {index_min}")


Index of maximum value: 5, Index of minimum value: 0


In [38]:
my_np_array = np.array([1, 5, 1, 1, 5, 7])

# Splitting the array into two parts using np.split().
# indices_or_sections=2 means splitting the array into 2 equal parts (if possible).
new_np_array = np.split(
    my_np_array,
    indices_or_sections=2  # Splitting into 2 parts
)

print("Array after splitting into 2 parts:", new_np_array)


Array after splitting into 2 parts: [array([1, 5, 1]), array([1, 5, 7])]


In [39]:
# perform (.) calculations.
my_np_array_1 = np.array([1, 2, 3])
my_np_array_2 = np.array([3, 4, 5])

# Printing the original arrays
print("Array 1:", my_np_array_1)
print("Array 2:", my_np_array_2)

# Calculating the dot product of the two arrays
# The dot product is calculated as: (1*3) + (2*4) + (3*5)
dot_product = np.dot(my_np_array_1, my_np_array_2)

print("Dot product of Array 1 and Array 2:", dot_product)


Array 1: [1 2 3]
Array 2: [3 4 5]
Dot product of Array 1 and Array 2: 26


In [41]:
my_2d_array_1 = np.array(
    [[2, 1, 3],
     [7, 5, 6]]
)

# Printing the shape of the original 2D array
# This will show (2, 3) because the array has 2 rows and 3 columns
print("Shape of the original array:", my_2d_array_1.shape)

# Transposing the matrix (swapping rows and columns)
# The result will have 3 rows and 2 columns, so the shape will be (3, 2)
print("Shape of the transposed array:", my_2d_array_1.T.shape)


Shape of the original array: (2, 3)
Shape of the transposed array: (3, 2)


In [42]:
print(np.mean(my_np_array_1))
print(np.median(my_np_array_1))
print(np.std(my_np_array_1))

2.0
2.0
0.816496580927726


In [43]:
# Vectorization

my_1d_array = np.array(
    [1, 2, 3, 4, 5]
)

print(my_1d_array)

my_1d_array % 2 == 1

[1 2 3 4 5]


array([ True, False,  True, False,  True])

In [44]:
for x in my_1d_array:
    x = x + 5

my_1d_array = my_1d_array + 5
print(my_1d_array)

[ 6  7  8  9 10]


In [47]:
w = np.array([1, 2])  # Shape: (2,)

# Creating a 2-dimensional array with shape (4, 2)
x = np.array([
    [3, 4],  # First row
    [5, 6],  # Second row
    [7, -8], # Third row
    [-5, -3] # Fourth row
])  # Shape: (4, 2)

# Broadcasting operation: The smaller array `w` (shape (2,)) will be broadcast across
# the larger array `x` (shape (4, 2)) for element-wise multiplication.
# The result is a new array where each row in `x` is multiplied by `w`.
result = w * x

print("Result of broadcasting multiplication:")
print(result)


Result of broadcasting multiplication:
[[  3   8]
 [  5  12]
 [  7 -16]
 [ -5  -6]]


In [48]:
array1 = np.array([1, 2])
array2 = np.array([3, 4])

# Performing element-wise multiplication
result = array1 * array2
print(result)


[3 8]
